### ISSUE TITLE
Fullstack Capstone Project Kanban Board

### ISSUE THREAD

**Issue by demesameneshoa** [mahammad-mostafa/tesla-booking-back-end#11]
## Hello there this is our team Kanban boards 🔢 
- Our Team Has Four Members Which are Listed Below: 
    @mahammad-mostafa 
    @ITurres 
    @78fatemanazari 
    @demesameneshoa 

Project URL for the `back-end` Kanban board https://github.com/users/mahammad-mostafa/projects/4
Project URL for the `front-end` Kanban board https://github.com/users/ITurres/projects/6/views/1
### Back-end Kanban Board Screenshot: 
![kanbanscreenshot](https://github.com/mahammad-mostafa/tesla-booking-back-end/assets/119149574/e7e10c4f-a571-4a4f-85f3-e7c9571569fd)

### Front-end Kanban Board Screenshot: 
![front-end kanban](https://github.com/mahammad-mostafa/tesla-booking-back-end/assets/119149574/2fbba004-ee5f-4174-a075-82b08fb7c3f5)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![297895621-bb105350-9d54-4597-bffb-e22cda0e2a92](https://github.com/mahammad-mostafa/tesla-booking-back-end/assets/57421823/052afebb-6f11-422f-9259-9e08495ee9b0)

However:

1- You've created 1 extra Kanban board for a total of 2.
2- One of the boards has names for the columns "Important notes, backlog, in progress, In review".
3- Not all cards are tasks.
4- Not all cards have been assigned to someone.
5- I cannot check if the tasks pointings are equal (nobody should have more than 5 points than any member) because of item 4.

Therefore:

- [ ] There should be only one Kanban board with all the tasks, even if the project spans 2 apps.
- [ ] Ensure your board contains only 4 columns named: "Todo, In progress, In review, Done".
- [ ] Please, kindly don't include any cards that are not tasks (like meet the team, etc).
- [ ] There shouldn't exist any card that hasn't been assigned to a person (or group of persons).
- [ ] Please make sure that after the above is done, nobody in the team has 5 more points than any other member.

__note and tip_:  While it is very commendable to do opinionated work and of course there are several ways to do this task, in a job environment we are _**required**_ to do what is _**required**_.  Chances are, on your brand new job, the same will apply to you._  👍 




Cheers and Happy coding!👏👏👏



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
